# ---------------------------------------------------------------------------
# StorageClasses EFS amb provisionament dinamic (Access Points automatics)
# ---------------------------------------------------------------------------
# Requereix: credencials AWS injectades al controller EFS CSI
# Veure: dynamic-efs.md per detalls
# ---------------------------------------------------------------------------

# StorageClass per WordPress (uid/gid 33 = www-data)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c70a17acfbf88764
  directoryPerms: "755"
  basePath: "/wordpress"
  uid: "33"
  gid: "33"
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
# StorageClass per MySQL (uid/gid 999 = mysql)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc-mysql
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c70a17acfbf88764
  directoryPerms: "700"
  basePath: "/mysql"
  uid: "999"
  gid: "999"
reclaimPolicy: Retain
volumeBindingMode: Immediate
