apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
# PV estatic per MySQL (Access Point: fsap-0db7a20b42ebceea1)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c70a17acfbf88764::fsap-0db7a20b42ebceea1
---
# PV estatic per WordPress (Access Point: fsap-016c0e43e40388baf)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-wordpress-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c70a17acfbf88764::fsap-016c0e43e40388baf
